DEMO_INCIDENTS = [
    {
        "id": "demo-001",
        "incident_code": "INC-001",
        "title": "Missing manhole cover",
        "summary": "Open manhole reported on a busy road with pedestrian safety risk.",
        "canonical_road": "Galle Road",
        "ward": "Bambalapitiya",
        "category": "Drains",
        "work_type": "Manhole",
        "severity": "critical",
        "report_count": 5,
        "priority_score": 95,
        "priority_level": "CRITICAL",
        "priority_reasons": [
            {"factor": "Safety / severity", "points": 35, "reason": "Open manhole creates immediate safety risk."},
            {"factor": "Road / public impact", "points": 20, "reason": "Main road."},
            {"factor": "Critical facility", "points": 15, "reason": "Public facility nearby."},
            {"factor": "Age / persistence", "points": 10, "reason": "Unresolved for several days."},
            {"factor": "Multiple reports", "points": 10, "reason": "Five reports support the incident."},
            {"factor": "Resident urgency", "points": 5, "reason": "High urgency."},
        ],
        "required_crew": "Drainage",
        "status": "Triaged",
        "classification_confidence": 0.98,
        "location_confidence": 0.95,
        "needs_review": False,
    },
    {
        "id": "demo-002",
        "incident_code": "INC-002",
        "title": "Large pothole near pharmacy",
        "summary": "Multiple reports describe a large pothole near the pharmacy creating vehicle damage risk.",
        "canonical_road": "Kirula Road",
        "ward": "Kirulapone",
        "category": "Roads",
        "work_type": "Pothole",
        "severity": "high",
        "report_count": 4,
        "priority_score": 76,
        "priority_level": "HIGH",
        "priority_reasons": [
            {"factor": "Safety / severity", "points": 28, "reason": "Vehicle hazard."},
            {"factor": "Road / public impact", "points": 20, "reason": "Important road."},
            {"factor": "Age / persistence", "points": 10, "reason": "Persistent issue."},
            {"factor": "Multiple reports", "points": 6, "reason": "Four reports."},
            {"factor": "Resident urgency", "points": 5, "reason": "High urgency."},
        ],
        "required_crew": "Road Surface",
        "status": "New",
        "classification_confidence": 0.96,
        "location_confidence": 0.92,
        "needs_review": False,
    },
    {
        "id": "demo-003",
        "incident_code": "INC-003",
        "title": "Streetlight outage",
        "summary": "Residents report a persistent streetlight outage leaving part of the lane dark.",
        "canonical_road": "Muhandiram Place",
        "ward": "Havelock Town",
        "category": "Street furniture",
        "work_type": "Streetlight",
        "severity": "medium",
        "report_count": 7,
        "priority_score": 58,
        "priority_level": "MEDIUM",
        "priority_reasons": [
            {"factor": "Safety / severity", "points": 18, "reason": "Night-time visibility impact."},
            {"factor": "Road / public impact", "points": 8, "reason": "Residential road."},
            {"factor": "Age / persistence", "points": 15, "reason": "Reported as persistent."},
            {"factor": "Multiple reports", "points": 10, "reason": "Seven reports."},
        ],
        "required_crew": "Lighting & Street Furniture",
        "status": "New",
        "classification_confidence": 0.94,
        "location_confidence": 0.90,
        "needs_review": False,
    },
    {
        "id": "demo-004",
        "incident_code": "INC-004",
        "title": "Fallen tree branch",
        "summary": "A fallen branch is obstructing part of the road. No supported specialist crew was identified.",
        "canonical_road": "Nawala Road",
        "ward": "Nawala",
        "category": "Trees",
        "work_type": "Unsupported",
        "severity": "medium",
        "report_count": 2,
        "priority_score": 46,
        "priority_level": "MEDIUM",
        "priority_reasons": [
            {"factor": "Safety / severity", "points": 18, "reason": "Road obstruction."},
            {"factor": "Road / public impact", "points": 20, "reason": "Important road."},
            {"factor": "Multiple reports", "points": 3, "reason": "Two reports."},
        ],
        "required_crew": "Manual Review",
        "status": "Needs Review",
        "classification_confidence": 0.99,
        "location_confidence": 0.88,
        "needs_review": True,
    },
]
